### ISSUE TITLE
Provide R8 file for Android

### ISSUE THREAD

**Issue by Siedlerchr** [snappdevelopment/JsonTree#112]
The new version gives an R8 error:

ERROR: R8: Missing class kotlinx.atomicfu.AtomicFU (referenced from: void com.sebastianneubauer.jsontree.AtomicLongWrapper.<init>())
Missing class kotlinx.atomicfu.AtomicLong (referenced from: kotlinx.atomicfu.AtomicLong com.sebastianneubauer.jsontree.AtomicLongWrapper.atomicLong and 2 other contexts)

**Comment by snappdevelopment** [comment]
Hi,
thanks for reporting this! I will take a look asap.

**Comment by snappdevelopment** [comment]
@Siedlerchr I just released a fix for this in version 2.4.1

**Comment by Siedlerchr** [comment]
Thanks for the quick fix and thanks for the great library!
