### ISSUE TITLE
Add contentPadding parameter

### ISSUE THREAD

**Issue by KlassenKonstantin** [snappdevelopment/JsonTree#47]
Hi, nice library, I might have found a use for it 🫶!

Since it's backed by a `LazyColumn` now, would it be possible to add the `contentPadding` parameter to `JsonTree` and just forward it to the `LazyColumn`? This way it would be possible to add padding without clipping the content during scroll.

**Comment by snappdevelopment** [comment]
Hi, thank you for using JsonTree :)
That's a good idea. I will try to add this asap

**Comment by snappdevelopment** [comment]
Hi @KlassenKonstantin 
I just released version 2.1.0 with the `contentPadding` parameter. 
You can check out the release notes here: https://github.com/snappdevelopment/JsonTree/releases

**Comment by KlassenKonstantin** [comment]
Works great 💯. Thanks for the quick response
