### ISSUE TITLE
Feature request: expand until level has multiple children

### ISSUE THREAD

**Issue by TheKeeperOfPie** [snappdevelopment/JsonTree#63]
Right now, when you click a heavily nested item

```
  ▾ {
    ▸ "one": { 1 item }
}
```

you get

```
  ▾ {
    ▾ "one": {
       ▸ "two": { 2 items }
      }
}
```

but I want

```
  ▾ {
    ▾ "one": {
       ▾ "two": {
           "three": 3,
           "four": 4
         }
      }
}
```

Similar to how a file browser/IDE expands single children folders/packages.

**Comment by snappdevelopment** [comment]
Hi @TheKeeperOfPie 
thanks for the suggestion! So you want that objects and arrays who only have one child also expand the child and so on, until there are at least two children or primitive values.
I will think about adding this feature. Maybe with a parameter to configure it.

**Comment by snappdevelopment** [comment]
@TheKeeperOfPie 
I added this feature in version 2.2.0. It can be configured by setting the `expandSingleChildren` parameter to true.
Thanks for the idea 👍
