### ISSUE TITLE
missing jar in maven central

### ISSUE THREAD

**Issue by KGumarov** [snappdevelopment/JsonTree#86]
Hi,

Maybe I don't understand something, but when I add a dependency according to the readme, Gradle can't find the required dependency.
Apparently it's not there; could you add it or clarify what I'm doing wrong?

https://repo1.maven.org/maven2/com/sebastianneubauer/jsontree/jsontree/2.2.0/

![image](https://github.com/user-attachments/assets/aa4588cd-036b-4f76-9d2e-b25355e0b1d8)

**Comment by snappdevelopment** [comment]
Hi KGumarov,
you don't need the line with `artifactUrls(..)`. `mavenCentral()` and the `implementation` line at the bottom is enough.
However it looks like you are trying to build a multiplatform app. This library uses Jetpack Compose, which means it only runs on Android. It doesn't support compose multiplatform right now.
