### ISSUE TITLE
Support Compose Multiplatform

### ISSUE THREAD

**Issue by ShreyashKore** [snappdevelopment/JsonTree#88]
I would like to use this library in a multi-platform project. As the library does not seem to have any dependency on Android it should be as easy as restructuring and changing the config. I'm happy to contribute the restructuring part. Publishing may require some changes, which will need to be taken care of.

And thanks for this amazing project :)

**Comment by snappdevelopment** [comment]
Hi Shreyash,

thanks for your interest in JsonTree! I saw that you already opened a PR for the multiplatform changes.
I also thought about converting it to a multiplatform library, so this is great. I will try to review your PR in the next couple days and then look into the publishing changes.

Thanks again!
